### ISSUE TITLE
Please update document. File not Found

### ISSUE THREAD

**Issue by thehung12a3** [codeskyblue/AutomatorX#14]
`pip install http://goandroid.qiniucdn.com/opencv_python-2.4.12-cp27-none-win_amd64.whl`
File not Found. I suggest you should change language to english

**Comment by codeskyblue** [comment]
Thanks for report this issue, the cdn provider got something wrong, fixed by change another download domain.

BTW: It is surprised me that there is some noticed this repo and make an issue. I'll think about change language to english if I got more time to do it.
