### ISSUE TITLE
It cannot find the image text?

### ISSUE THREAD

**Issue by thehung12a3** [codeskyblue/AutomatorX#15]
I used `d.exists('a1.png')` but It cannot find the image text.
Ex: Webpage not available in browser
![a](https://cloud.githubusercontent.com/assets/4132665/14586560/0bfefd90-04c6-11e6-9f25-db8a0ec7b56a.PNG)
![a1](https://cloud.githubusercontent.com/assets/4132665/14586561/0f790aba-04c6-11e6-88fd-b83ef8dd06c0.PNG)
How to fix it ?

**Comment by codeskyblue** [comment]
？？？ what wrong?

**Comment by thehung12a3** [comment]
Sorry, This is mistake. Can you send for me skype or gmail. I want ask you
some questions

2016-04-17 22:12 GMT+07:00 shengxiang <notifications@github.com>:

> ？？？ what wrong?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeskyblue/AutomatorX/issues/15#issuecomment-211042570>
>



-- 
*--------------------------------------------------------------------------------------------------------*


*Email: hoangthehung92@gmail.com <hoangthehung92@gmail.com> , Skype
Chat: hunghoangthe92Cell Phone Number: +84 1658885289,  company:
smartdev.vn <http://smartdev.vn>Address:  103 Nguyen Tri Phuong
Street, Thanh Khe** District, Da Nang City, Vietnam*

**Comment by thehung12a3** [comment]
Can It make auto testing  on real device of ios?

**Comment by codeskyblue** [comment]
@thehung12a3 Not very familar with iOS develop for now, and atx not support ios for now.
I studying on develop ios app with reactnative recently, but it is very hard to say when will see any progress. my gmail is <codeskyblue at gmail.com>
