### ISSUE TITLE
issue RPC server not started

### ISSUE THREAD

**Issue by thehung12a3** [codeskyblue/AutomatorX#17]
My scenario:
+ Quit device -> Start device -> workflow ->  Quit device -> Start device -> workflow --> .... (loop it )

Error: After a period then workflow don't work. It's pause

**Comment by codeskyblue** [comment]
How did you Quit device? Can you show detail steps?

**Comment by thehung12a3** [comment]
Hi @codeskyblue 

![untitled](https://cloud.githubusercontent.com/assets/4132665/15353760/b8dca7f4-1d14-11e6-90bb-83c8bc1e2162.png)

**Comment by codeskyblue** [comment]
那你的手机是什么牌子的？
