### ISSUE TITLE
How to set value for edittext

### ISSUE THREAD

**Issue by thehung12a3** [codeskyblue/AutomatorX#18]
![capture](https://cloud.githubusercontent.com/assets/4132665/14941547/d25f4a9a-0fc9-11e6-8e7f-8f928e0e2175.PNG)

**Comment by codeskyblue** [comment]
d.text("Some text")

**Comment by codeskyblue** [comment]
Doc has been added to readme. you need to use the latest dev version.

usage:

```
d.type("hello", enter=True)
```
