### ISSUE TITLE
Sometime, It stopped in loop. I don't know why?

### ISSUE THREAD

**Issue by thehung12a3** [codeskyblue/AutomatorX#31]
```
thread = threading.Thread(target=self.run_test,
args=(self.event, db, self.app_status_queue,))
thread.daemon = True
self.status_run_app = True
self.event.set()
thread.start()
```

func loop:

```
def run_test()
   while true:
     u = atx.connect()
    #action test ...
     kill adb
    
```

My log.txt
[log.txt](https://github.com/codeskyblue/AutomatorX/files/306072/log.txt)
[log-2.txt](https://github.com/codeskyblue/AutomatorX/files/306077/log-2.txt)

**Comment by codeskyblue** [comment]
actually atx  will raise exception in  some condition.. you should use try. ... catch

**Comment by thehung12a3** [comment]
I checked but It's not raise any exception

**Comment by codeskyblue** [comment]
Exceptions will be ignored in python theading. you must add try except manually if you want see some exceptions

**Comment by thehung12a3** [comment]
Where should I add it ?  Line of code in theading. ?
Ex:
```
def run_test()
   while true:
   try:
      u = atx.connect()
   except Exception as e:
       # to do
   try:
     u.click(text="ABC")
  except Exception as e:
   # to do
``

**Comment by codeskyblue** [comment]
yeah it should works this way

**Comment by codeskyblue** [comment]
@thehung12a3 resolved?

**Comment by thehung12a3** [comment]
@codeskyblue  No.

**Comment by codeskyblue** [comment]
额

**Comment by codeskyblue** [comment]
Too long time, closed for now, you got any progress, please reopen it.

**Comment by henryhoang92** [comment]
![error](https://cloud.githubusercontent.com/assets/4132665/16268169/742f0160-38b7-11e6-94a7-4e4717229edd.PNG)

Hi @codeskyblue 
It stop's at that positions

**Comment by wuxc** [comment]
@henryhoang92 
1. what do you mean by 'stop', exit or hung? 
2. is all rpcs fail or just some special ones? 
3. is it phone related? have you tried on another phone?

**Comment by henryhoang92** [comment]
After execute command log.debug("TA_1") then It isn't return anything. Stop at  `command return  _method_obj(*args, **kwargs)`

+ No return any exceptions. Just stop at that and don't execute any command line. I think It's problem with RPC server.

+I want to return  an exception for problem . how to do it?
