### ISSUE TITLE
4.1.2的android设备，无法点击横屏的图片

### ISSUE THREAD

**Issue by minqi1213** [codeskyblue/AutomatorX#33]
如题，游戏进入横屏状态，但atx还认为4.1的设备在竖屏状态下。导致无法点击图片

**Comment by codeskyblue** [comment]
多提供点消息呀，手机型号，之类的，反正有办法让我重新复现的内容

**Comment by minqi1213** [comment]
4.1.2的手机调试横屏游戏 是gui截图 在gui里尝试点击截图 无效果。通过点击坐标发现无法自动识别手机已经横屏，还是点击竖屏状态下的坐标

**Comment by codeskyblue** [comment]
If rotation is still wrong, use `d.screen_rotation = 1` to set to the right rotation.
