### ISSUE TITLE
红米 note Android4.4.4 录屏提示minicap错误

### ISSUE THREAD

**Issue by codeskyblue** [codeskyblue/AutomatorX#48]
## What steps will reproduce the problem?
```
python -m atx screenrecord -o out.avi
```
## What is the expected output?

正确录制视频
## What do you see instead?

异常报错
## Do you have any log or screenshots?

```
C:\Users\Administrator>python -m atx screenrecord -o out.avi
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\atx\adbkit\mixins.py", line 152, in _pull
assert p.poll() is None
AssertionError
Process died.
ERROR: invalid format for -P, need <w>x<h>@<w>x<h>/{0|90|180|270}

minicap died
```

**Comment by wuxc** [comment]
looks like install of minicap failed. so I changed to os.system. I tried on HongMi-Note 4.4.4 and it looked ok. Please try again.
