### ISSUE TITLE
集成所有常用功能的APK

### ISSUE THREAD

**Issue by codeskyblue** [codeskyblue/AutomatorX#50]
* [x] Utf7IME输入法
* [x] 屏幕常亮 Keep Screen WakeUP
* [x] 自动安装软件,自动确认权限 Auto confirm installation, permissions

**Comment by xudafeng** [comment]
@codeskyblue wakeup UIAutomator 实现就行吧

**Comment by xudafeng** [comment]
@codeskyblue wakeup UIAutomator 实现就行吧

**Comment by xudafeng** [comment]
@codeskyblue wakeup UIAutomator 实现就行吧

**Comment by codeskyblue** [comment]
@xudafeng 是需要保持常量的功能，即使测试不在运行的时候，也需要常量

**Comment by xudafeng** [comment]
@codeskyblue https://github.com/xudafeng/unlock-apk/blob/master/src/xdf/android_unlock/MainActivity.java#L36

**Comment by codeskyblue** [comment]
@xudafeng 大神，你可真是什么都写过呀
