### ISSUE TITLE
锤子坚果U1，无法实现静默测试。

### ISSUE THREAD

**Issue by CoderMageFox** [codeskyblue/AutomatorX#59]
环境：坚果U1（YQ601），Android 4.4.4，Smarisan OS 2.1.2 + atx环境
问题：无法实现静默测试。
相关设置：https://cloud.githubusercontent.com/assets/20943228/17580650/dd202342-5fd2-11e6-8077-f97d6063cf97.png
https://cloud.githubusercontent.com/assets/20943228/17580651/dd314226-5fd2-11e6-89eb-f5ddb1e765c0.png
https://cloud.githubusercontent.com/assets/20943228/17580654/e0b49024-5fd2-11e6-9c8f-0cb255691500.png
https://cloud.githubusercontent.com/assets/20943228/17580652/dd71b2a2-5fd2-11e6-8c5c-3953d366df29.png
运行简单脚本test.py后，显示
https://cloud.githubusercontent.com/assets/20943228/17580729/61456d12-5fd3-11e6-8c59-025eb3164c47.png
https://cloud.githubusercontent.com/assets/20943228/17580730/623d48a2-5fd3-11e6-8367-f2dbc4f62095.png
自动安装显示打开。
https://cloud.githubusercontent.com/assets/20943228/17580775/bf46c67c-5fd3-11e6-8c17-36c86f2953ea.png
目测应该是锤子手机自己设置的.....魅族MX3测试就没这个问题。在锤子手机官网找到帖子：
http://bbs.smartisan.com/thread-152267-1-1.html
应该是锤子手机独有问题。

**Comment by codeskyblue** [comment]
哥，格式稍微调整下

**Comment by BigWavelet** [comment]
@CoderMageFox  1.0.2版的应该解决了这个问题，你可以装一下最新的试试哈

**Comment by codeskyblue** [comment]
@BigWavelet 你说的1.0.2版是指什么？锤子的版本吗？

**Comment by BigWavelet** [comment]
@codeskyblue  ATX Assistant 1.0.2版
